### ISSUE TITLE
Add tests for ChessChaos.Core.ChessBoard

### ISSUE THREAD

**Issue by rokiboxofficial** [rokiboxofficial/ChessChaos#13]
Add tests for all methods.

Probably tests cases for FromPoints fluent api:
- Check that FromPoint throw an exception if move from FROM to TO is not possible
- Check that ValidateMove provide correct mvoe
- Check that ValidateBoard provide board state AFTER move was applied to board
- Check that ValidateBoard rollback applied move if accessor delegate throwed an exception.
etc.

**Comment by Electrician25** [comment]
Check that FromPoint throw an exception if move from FROM to TO is not possible.
Methods: WhenMovingPieces_AndMovePieceOnNotExistPoint_ThrowException, WhenMovingPieces_AndPieceKingMoveIsNotCorrect_ThrowException, WhenMovingPieces_AndPieceBishopMoveIsNotCorrect_ThrowException

**Comment by Electrician25** [comment]
Check that ValidateMove provide correct mvoe.
Method: WhenMovingPieces_AndMoveIsCorrect_WhenMoveShouldBeTrue

**Comment by Electrician25** [comment]
Check that ValidateBoard provide board state AFTER move was applied to board.
Method: WhenMovingPieces_AndMovingPieceIsNotApply_WhenPointShouldBeComeBack

**Comment by Electrician25** [comment]
Check that ValidateBoard rollback applied move if accessor delegate throwed an exception.
Method:  WhenMovingPieces_AndMovingPieceIsApply_WhenMoveShouldBeSaved

**Comment by Electrician25** [comment]
Check that FromPoint throw an exception if move from FROM to TO is not possible.
Method: WhenMovingPieces_AndPieceKingMoveIsNotCorrect_ThrowException and WhenMovingPieces_AndPieceBishopMoveIsNotCorrect_ThrowException

**Comment by Electrician25** [comment]
Check that ValidateMove provide correct mvoe.
Method:WhenMovingPieces_AndMoveIsCorrect_WhenMoveShouldBeTrue

**Comment by Electrician25** [comment]
Check that ValidateBoard provide board state AFTER move was applied to board.
Method: WhenMovingPieces_AndMovingPieceIsApply_WhenMoveShouldBeSaved

**Comment by Electrician25** [comment]
Check that ValidateBoard rollback applied move if accessor delegate throwed an exception.
Method: WhenMovingPieces_AndMovingPieceIsNotApply_WhenPointShouldBeComeBack

**Comment by Electrician25** [comment]
If ValidateBoard() throw exception when revert move:
WhenMovingPieces_AndBoardThrowException_ThrowExceptionAndRevertMove

**Comment by Electrician25** [comment]
If ValidateBoard() throw exception when revert move:
Method: WhenMovingPieces_AndBoardThrowException_RevertMove

**Comment by Electrician25** [comment]
if moving piece and point on the board not exist. 
Method: WhenMovingPieces_AndBoardNotExistToPoint_ThenThrowException

**Comment by Electrician25** [comment]
Если король ходит туда кода ходить по правилам не может, ошибка.
WhenMovingPieces_AndPieceKingMoveIsNotCorrect_ThrowException

**Comment by Electrician25** [comment]
Если слон ходит туда кода ходить по правилам не может, ошибка.
WhenMovingPieces_AndPieceBishopMoveIsNotCorrect_ThrowException

**Comment by Electrician25** [comment]
Если move верный, ошибки быть не должно.
WhenMovingPieces_AndMoveIsCorrect_ThenMoveShouldBeTrue

**Comment by Electrician25** [comment]
Если корректный ход был сделан и не был сохранён через метод apply, ход должен откатиться 
WhenMovingPieces_AndMovingPieceIsNotApply_ThenPointShouldBeComeBack

**Comment by Electrician25** [comment]
Если корректный ход был сделан и был сохранён через метод apply, ход должен примениться
WhenMovingPieces_AndMovingPieceIsApply_ThenMoveShouldBeSaved

**Comment by Electrician25** [comment]
Если ход был сделан и доска не валидна ход должен откатиться.
WhenMovingPieces_AndBoardThrowException_RevertMove

**Comment by Electrician25** [comment]
Если ход был сделан верный и move не валиден, то должен откатится ход.
WhenMovingPieces_AndMoveThrowException_RevertMove

**Comment by Electrician25** [comment]
Если фигура ходит на точку которой нет на доске, должна выбрасыватсья ошибка 
WhenMovingPieces_AndBoardNotExistToPoint_ThenThrowException
